version: "3.9"

services:
  web-server:
    build: frontend
    ports: 
      - 3000:3000
    
  auth-service:
    build: auth-service/
    ports: 
      - 4000:4000
    links:
      - db
    environment:
      MONGO_URI: mongodb://db:27017
  recipe-service:
    build: recipe-service/
    ports: 
      - 4001:4001
    links:
      - db
    environment:
      MONGO_URI: mongodb://db:27017
  db:
    image: mongo